export const TOGGLE_COLLAPSED_QUICKPANEL = 'TOGGLE_COLLAPSED_QUICKPANEL';
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSED_NAV';
export const CHANGE_COLOR_OPTION = 'CHANGE_COLOR_OPTION';
export const CHANGE_THEME = 'CHANGE_THEME';
